FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./

ENV DB_HOST=postgres
ENV DB_PORT=5432
ENV DB_USERNAME=admin
ENV DB_PASSWORD=admin123
ENV DB_DATABASE=aprobaciones_db
ENV PORT=3000

EXPOSE 3000

CMD ["npm", "run", "start:prod"]